CREATE TABLE `pos_master_produk` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`KODE` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`NAMA` VARCHAR(150) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`HARGA` INT NULL DEFAULT NULL,
	`SATUAN` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`JENIS` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`MERK` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`TIPE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KATEGORI_MARKETING` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`SUPPLIER` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`STATUS` ENUM('Aktif','Tidak Aktif',' Diskontinu','Kontinu') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`DESKRIPSI` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BENEFIT_PRODUK` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BARCODE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`GAMBAR` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BERAT` SMALLINT NULL DEFAULT NULL,
	`REGION` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	`CREATED_BY` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`UPDATED_BY` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `KODE` (`KODE`) USING BTREE,
	INDEX `KeySatuan` (`SATUAN`) USING BTREE,
	INDEX `KeyJenis` (`JENIS`) USING BTREE,
	INDEX `KeyMerk` (`MERK`) USING BTREE,
	INDEX `keySupplier` (`SUPPLIER`) USING BTREE,
	INDEX `keyKategoriMarketing` (`KATEGORI_MARKETING`) USING BTREE,
	INDEX `keyRegion` (`REGION`) USING BTREE,
	INDEX `kode_master_produk` (`KODE`) USING BTREE,
	CONSTRAINT `pos_master_produk_ibfk_1` FOREIGN KEY (`JENIS`) REFERENCES `pos_jenis` (`JENIS`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `pos_master_produk_ibfk_2` FOREIGN KEY (`MERK`) REFERENCES `pos_merek` (`MEREK`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `pos_master_produk_ibfk_3` FOREIGN KEY (`SATUAN`) REFERENCES `pos_satuan` (`SATUAN`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `pos_master_produk_ibfk_4` FOREIGN KEY (`KATEGORI_MARKETING`) REFERENCES `pos_kategori_marketing` (`KODE`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `pos_master_produk_ibfk_5` FOREIGN KEY (`REGION`) REFERENCES `pos_region` (`REGION`) ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT `pos_master_produk_ibfk_6` FOREIGN KEY (`SUPPLIER`) REFERENCES `pos_supplier_produk` (`KODE`) ON UPDATE CASCADE ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2286
;

CREATE TABLE `pos_satuan` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`SATUAN` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `SATUAN` (`SATUAN`) USING BTREE,
	INDEX `idx_satuan` (`SATUAN`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=64
;

CREATE TABLE `pos_jenis` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`JENIS` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `JENIS` (`JENIS`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=186
;

CREATE TABLE `pos_merek` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`MEREK` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `MEREK` (`MEREK`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=20
;

CREATE TABLE `pos_region` (
	`ID` TINYINT NOT NULL AUTO_INCREMENT,
	`REGION` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `REGION` (`REGION`) USING BTREE,
	INDEX `idx_region` (`REGION`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;


CREATE TABLE `sy_outlet` (
	`ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`NAMA` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`KODE_OUTLET` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`AKUN` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`FUNGSI` ENUM('Utama','Gudang','Cabang') NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`TIPE` ENUM('Kitchen','Outlet','FLC') NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`REGION` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`TELEGRAM_SALES_ONLINE` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`DETAIL_OUTLET` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LATITUDE` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`LONGITUDE` VARCHAR(25) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`created_at` TIMESTAMP NULL DEFAULT NULL,
	`updated_at` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=158
;

CREATE TABLE `pos_supplier` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`KODE` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`NAMA` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ALAMAT` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KOTA` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`HP` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`REKENING` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`ATAS_NAMA` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`BANK` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KATEGORI` ENUM('FLC','OUTLET') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`VISIBILITY` ENUM('On','Off') NOT NULL DEFAULT 'On' COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `KODE` (`KODE`) USING BTREE,
	INDEX `idx_kode` (`KODE`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=94
;


CREATE TABLE `pos_stok_outlet` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NIP` VARCHAR(6) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KODE` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`STOK_SISTEM` INT NULL DEFAULT '0',
	`STOK_PESANAN` INT NULL DEFAULT NULL,
	`PRE_ADJUSTMENT` INT NULL DEFAULT '0',
	`HISTORY_PRE_ADJUSTMENT` INT NULL DEFAULT NULL,
	`HISTORY_ADJUSTMENT` INT NULL DEFAULT NULL,
	`KODE_OUTLET` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`REGION` VARCHAR(1) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` DATETIME NULL DEFAULT NULL,
	`UPDATED_AT` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `kode_stok_outlet` (`KODE`) USING BTREE,
	INDEX `REGION` (`REGION`) USING BTREE,
	INDEX `KODE_OUTLET` (`KODE_OUTLET`) USING BTREE,
	INDEX `OutletRegion` (`KODE_OUTLET`, `REGION`) USING BTREE,
	FULLTEXT INDEX `KODE` (`KODE`, `KODE_OUTLET`)
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=158664
;

CREATE TABLE `pos_kategori_marketing` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`KODE` VARCHAR(5) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	`CREATED_AT` TIMESTAMP NULL DEFAULT (CURRENT_TIMESTAMP),
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `KODE` (`KODE`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=23
;

CREATE TABLE `pos_supplier_produk` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`KODE` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`NAMA` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KATEGORI` ENUM('FLC','OUTLET') NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`KETERANGAN` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`CREATED_AT` TIMESTAMP NULL DEFAULT NULL,
	`UPDATED_AT` TIMESTAMP NULL DEFAULT NULL,
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `KODE` (`KODE`) USING BTREE,
	INDEX `idx_kode` (`KODE`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=8
;
